version: "3.6"
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: ~
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes: [ ./docker/db/data:/var/lib/mysql ]
    ports: [ 3333:3306 ]
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - db
    restart: always
    volumes: [ ./src:/var/www/html ]
    ports: [ 80:80 ]